### PR TITLE
Bugfix capital letter replacement

### PR DESCRIPTION
**Pull request by maximilianmozes**
PR related to the recent bug w.r.t. the context-preserving replacement. I identified and fixed the bug causing the strange results. @ben-aaron188 please have a look and test the updated code. We should proceed in the following order:
1. Test NETANOS offline (use this code base).
2. Deploy updated code to the server.
3. Test NETANOS when deployed on the server.

Thanks!

### CODE REVIEW

**Comment by ben-aaron188** [comment]
@maximilianmozes Sounds good to me. I tested the odd results we had and they seem fine now. So I'm happy to go ahead as you suggest.

- [x] Test NETANOS offline (use this code base).
- [x] Deploy updated code to the server.
- [x] Test NETANOS when deployed on the server.

**Comment by maximilianmozes** [comment]
Thanks @ben-aaron188. I deployed the code and kindly ask you to test it. :)

**Comment by ben-aaron188** [comment]
@maximilianmozes Tested it: it does not anonymize (did it in FF and Chrome, both with file menu upload and d&d). I suspect it's either the server or dependency issues (e.g. `drag_and_drop.css` seems not to be linked). Can you check?

**Comment by maximilianmozes** [comment]
@ben-aaron188 Sorry, the server wasn't running. Should work now.

**Comment by ben-aaron188** [comment]
@maximilianmozes Works. I'd say we're good to announce it. Will do so.

**Pull request merged**
